services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend01
      - backend02
      - backend03

  backend01:
    build:
      context: ./server
    # environment:
    #   NODE_ENV: production

  backend02:
    build:
      context: ./server
    # environment:
    #   NODE_ENV: production

  backend03:
    build:
      context: ./server
    # environment:
    #   NODE_ENV: production
